name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  main:
    name: Run main jobs
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'issei-m2') ||
      (github.event_name != 'pull_request_target' && github.actor != 'issei-m2')
    steps:
      - uses: actions/checkout@v2

      - run: git log -n 1

      - name: Run script with NON_CRITICAL
        run: node ./run.js
        env:
          SECRET_NAME: NON_CRITICAL
          SECRET_VALUE: ${{ secrets.NON_CRITICAL }}

      - name: Run script with CRITICAL
        run: node ./run.js
        env:
          SECRET_NAME: CRITICAL
          SECRET_VALUE: ${{ secrets.CRITICAL }}
