name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  main:
    name: Run main jobs
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'issei-m2') ||
      (github.event_name != 'pull_request_target' && github.actor != 'issei-m2')
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: git log -n 1

      - name: Run script with SENSITIVE_INFO
        run: node ./run.js
        env:
          SECRET_NAME: SENSITIVE_INFO
          SECRET_VALUE: ${{ secrets.SENSITIVE_INFO }}

